### ISSUE TITLE
com.googlecode.d2j.DexException: not support version.

### ISSUE THREAD

**Issue by cr4ck32** [b-mueller/apkx#5]
Hi,
I have the following error:
Extracting mod.apk to mod
Converting: classes2.dex -> classes2.jar (dex2jar)
dex2jar mod/classes2.dex -> mod/classes2.jar
com.googlecode.d2j.DexException: not support version.
	at com.googlecode.d2j.reader.DexFileReader.<init>(DexFileReader.java:151)
	at com.googlecode.d2j.reader.DexFileReader.<init>(DexFileReader.java:211)
	at com.googlecode.dex2jar.tools.Dex2jarCmd.doCommandLine(Dex2jarCmd.java:104)
	at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:288)
	at com.googlecode.dex2jar.tools.Dex2jarCmd.main(Dex2jarCmd.java:32)
Decompiling to mod/src (cfr)

I have seen that the solution could be this:
https://github.com/DexPatcher/dex2jar/releases

but I don't know how to implement it, could you please give me the steps to fix it? 
Thank you.

**Comment by Popbrain** [comment]
@cr4ck32 
I worked with the following steps, please try it. 👍 

#### 1. Install dex2jar by brew
```
brew install dex2jar
```
#### 2. Download [https://github.com/DexPatcher/dex2jar/releases](https://github.com/DexPatcher/dex2jar/releases), And Unzip.
#### 3. Move to `/usr/local/Cellar/dex2jar/VERSION/libexec` in local.
#### 3.  Replace `/usr/local/Cellar/dex2jar/VERSION/libexec/lib` to `dex-tools-2.1-20190905-lanchon/lib` of the Unziped.
